
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156/proj-courses
owner: ucsb-cs156
repo_name: proj-courses
pull_requests: [{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-migrate-to-lib-jobs","number":314,"title":"Migrate jobs system to lib-jobs v0.1.6 (shared library)","url":"https://github.com/ucsb-cs156/proj-courses/pull/314"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"s26-02-pr54","number":312,"title":"S26 02 pr54 --- improvements to modal for creating schedules.","url":"https://github.com/ucsb-cs156/proj-courses/pull/312"}]
