name: 42-deploy-pr-to-dokku.yml
on:
  pull_request:
    types: [labeled]

env:
  GITHUB_TOKEN: ${{ secrets.PAT }}

jobs:
  has_deploy_label:
    name: Has Deploy Label
    runs-on: ubuntu-latest
    outputs:
      has-label: ${{ steps.has_deploy_label.outputs.has_deploy_label }}
    env:
      DEPLOY_LABEL: ${{ github.event.label.name }}
      PR_URL: ${{ github.event.pull_request.html_url }}
    steps:
      - name: "Check for Deploy Label"
        id: has_deploy_label
        run: |
          if [ "$DEPLOY_LABEL" == "Dokku Deploy" ]; then
            gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/ucsb-cs156-s25/dokku-sync/actions/workflows/00-sync-a-PR.yml/dispatches \
            -f ref='main' \
            -f "inputs[pr_url]=$PR_URL"
          else
            echo "not deploy label - skipping"
          fi
          
